name: Run finalwork tests

on:
  push:
    branches:
      - "finalwork"
  pull_request:
    branches:
      - "finalwork"

jobs:
  testing:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        working-directory: ./finalwork/UItests
        run: npm install
      - name: Run UI Tests
        working-directory: ./finalwork/UItests
        run: npm run test:cucumber
 