name: Run unit tests

on:
  push:
    branches:
      - "main1"
  pull_request:
    branches:
      - "lesson9_hw"

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        working-directory: ./lesson9_hw/mocha
        run: npm install
      - name: Run Unit Test
        working-directory: ./lesson9_hw/mocha
        run: npm run test
